---
- name: Download Magento Downloader 
  get_url: url=http://www.magentocommerce.com/downloads/assets/{{ mag_version }}/magento-{{ mag_version }}.tar.gz dest=/srv/magento-{{ mag_version }}.tar.gz

- name: Extract Archive
  command: chdir=/srv/ /bin/tar xvf magento-{{ mag_version }}.tar.gz creates=/srv/magento

- name: Add group "magento"
  group: name=magento

- name: Add user "magento"
  user: name=magento group=magento home=/srv/magento/

- name: Change ownership of Magento installation
  file: path=/srv/magento/ owner=magento group=magento state=directory recurse=yes

- name: Create Magento database
  mysql_db: name={{ mag_db_name }} state=present

- name: Create Magento database user
  mysql_user: name={{ mag_db_user }} password={{ mag_db_password }} priv={{ mag_db_name }}.*:ALL host='localhost' state=present